package:
  name: libgd
  version: 2.1.1

build:
  number: 1

source:
  git_url: https://github.com/libgd/libgd # [win]
  
  fn: libgd-2.1.2.tar.gz # [not win]
  url: https://bitbucket.org/libgd/gd-libgd/downloads/libgd-2.1.2.tar.gz # [not win]
  # NOTE: the tarball on github does not have a configure script
  #       if you install all the autotools deps, it shoudl work
  #       with the "bootstrap.sh" script, but this source version
  #       is easier, with a configure script ready to go
  #       the gd devs indicated that they will probably put
  #       configured source tarball on github at some point...
  

extra:
   recipe_maintainer : https://github.com/NOAA-ORR-ERD/py_gd

about:
    home: http://libgd.github.io/


requirements:
  build:
    - libpng
    - jpeg
    - freetype
    - zlib
    

  run:
    - libpng
    - jpeg
    - freetype
    - zlib
